# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Stumeet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "SwiftLint"
  
  pod 'LookinServer', :configurations => ['Debug']

  target 'StumeetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StumeetUITests' do
    # Pods for testing
  end

end